# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

# list any PHP version you want to test against
php:
  # using major version aliases
  # aliased to 5.2.17
  # - 5.2
  # aliased to a recent 5.3.x version
  - 5.3
  # aliased to a recent 5.4.x version
  # - 5.4

# optionally specify a list of environments, for example to test different RDBMS
env:
  - DB=mysql
  # - DB=pgsql

# execute any number of scripts before the test run, custom env's are available as variables
before_script:
  # - if [[ "$DB" == "pgsql" ]]; then psql -c "DROP DATABASE IF EXISTS hello_world_test;" -U postgres; fi
  # - if [[ "$DB" == "pgsql" ]]; then psql -c "create database hello_world_test;" -U postgres; fi
  # - if [[ "$DB" == "mysql" ]]; then mysql -e "create database IF NOT EXISTS hello_world_test;" -uroot; fi
  - mysql -uroot -p$MYSQL_ROOT_PASSWORD -v -e 'CREATE DATABASE `quizmo_dev`;'
  - mysql -uroot -p$MYSQL_ROOT_PASSWORD -v -e "CREATE USER 'quizmo_dev'@'localhost' IDENTIFIED BY 'quizmo_dev';"
  - mysql -uroot -p$MYSQL_ROOT_PASSWORD -v -e "GRANT ALL PRIVILEGES ON *.* TO 'quizmo_dev'@'localhost' WITH GRANT OPTION;"
  - quizmo/protected/yiic migrate --interactive=0

# omitting "script:" will default to phpunit
# use the $DB env variable to determine the phpunit.xml to use
script: phpunit --configuration quizmo/protected/tests/phpunit.xml --coverage-text unit

# configure notifications (email, IRC, campfire etc)
notifications:
  #irc: "irc.freenode.org#travis"
  email: "jcleveng@fas.harvard.edu"
