<?php
/**
 * @copyright Copyright (c) 2012 The President and Fellows of Harvard College
 * @license Use of this source code is governed by the LICENSE file found in the root of this project.
 */

/*
--------------------------------------------------------
--  DDL for Table QUIZMO_RESPONSE
--------------------------------------------------------

  CREATE TABLE "ISITESTOOLS"."QUIZMO_RESPONSE" 
   (	"RESPONSE_ID" NUMBER, 
	"QUESTION_ID" NUMBER, 
	"QUESTION_TYPE" VARCHAR2(1 BYTE), 
	"USER_ID" VARCHAR2(10 BYTE), 
	"SCORE_STATE" VARCHAR2(1 BYTE), 
	"SCORE" NUMBER DEFAULT '0', 
	"DATE_MODIFIED" DATE, 
	"MODIFIED_BY" VARCHAR2(10 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ISITESTOOLS" ;
--------------------------------------------------------
--  DDL for Index SYS_C0037193
--------------------------------------------------------

  CREATE UNIQUE INDEX "ISITESTOOLS"."SYS_C0037193" ON "ISITESTOOLS"."QUIZMO_RESPONSE" ("RESPONSE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ISITESTOOLS" ;
--------------------------------------------------------
--  DDL for Index QUIZMO_RESPONSE_QUESTION_ID
--------------------------------------------------------

  CREATE INDEX "ISITESTOOLS"."QUIZMO_RESPONSE_QUESTION_ID" ON "ISITESTOOLS"."QUIZMO_RESPONSE" ("QUESTION_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ISITESTOOLS" ;
--------------------------------------------------------
--  DDL for Index QUIMZO_RESPONSE_QUESTION_TYPE
--------------------------------------------------------

  CREATE INDEX "ISITESTOOLS"."QUIMZO_RESPONSE_QUESTION_TYPE" ON "ISITESTOOLS"."QUIZMO_RESPONSE" ("QUESTION_TYPE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ISITESTOOLS" ;
--------------------------------------------------------
--  DDL for Index QUIZMO_RESPONSE_USER_ID
--------------------------------------------------------

  CREATE INDEX "ISITESTOOLS"."QUIZMO_RESPONSE_USER_ID" ON "ISITESTOOLS"."QUIZMO_RESPONSE" ("USER_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ISITESTOOLS" ;
--------------------------------------------------------
--  DDL for Index QUIZMO_RESPONSE_MODIFIER
--------------------------------------------------------

  CREATE INDEX "ISITESTOOLS"."QUIZMO_RESPONSE_MODIFIER" ON "ISITESTOOLS"."QUIZMO_RESPONSE" ("MODIFIED_BY") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ISITESTOOLS" ;
--------------------------------------------------------
--  Constraints for Table QUIZMO_RESPONSE
--------------------------------------------------------

  ALTER TABLE "ISITESTOOLS"."QUIZMO_RESPONSE" MODIFY ("RESPONSE_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ISITESTOOLS"."QUIZMO_RESPONSE" MODIFY ("QUESTION_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ISITESTOOLS"."QUIZMO_RESPONSE" MODIFY ("QUESTION_TYPE" NOT NULL ENABLE);
 
  ALTER TABLE "ISITESTOOLS"."QUIZMO_RESPONSE" MODIFY ("USER_ID" NOT NULL ENABLE);
 
  ALTER TABLE "ISITESTOOLS"."QUIZMO_RESPONSE" MODIFY ("SCORE" NOT NULL ENABLE);
 
  ALTER TABLE "ISITESTOOLS"."QUIZMO_RESPONSE" ADD PRIMARY KEY ("RESPONSE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "ISITESTOOLS"  ENABLE;


"RESPONSE_ID" NUMBER, 
"QUESTION_ID" NUMBER, 
"QUESTION_TYPE" VARCHAR2(1 BYTE), 
"USER_ID" VARCHAR2(10 BYTE), 
"SCORE_STATE" VARCHAR2(1 BYTE), 
"SCORE" NUMBER DEFAULT '0', 
"DATE_MODIFIED" DATE, 
"MODIFIED_BY" VARCHAR2(10 BYTE)

*/
require_once("Autoincrement.php");

class m120402_195445_Responses extends CDbMigration
{
	public function up()
	{
		$this->createTable('RESPONSES', array(
			'ID' => 'pk',
			'QUESTION_ID' => 'integer NOT NULL',
			'QUESTION_TYPE' => 'string NOT NULL',
			'USER_ID' => 'integer NOT NULL',
			'RESPONSE' => 'text',
			'SCORE_STATE' => "string",
			'SCORE' => 'integer',
			'DATE_MODIFIED' => 'datetime',
			'MODIFIED_BY' => 'integer',
		));	
		
		Autoincrement::up('RESPONSES', Yii::app()->db->driverName);


		
	}

	public function down()
	{
		Autoincrement::down('RESPONSES', Yii::app()->db->driverName);


		$this->dropTable('RESPONSES');
	}

	/*
	// Use safeUp/safeDown to do migration with transaction
	public function safeUp()
	{
	}

	public function safeDown()
	{
	}
	*/
}
